# Generated by Django 4.2.1 on 2023-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sock_alter_worn_options_alter_worn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='socks',
            field=models.ManyToManyField(to='main_app.sock'),
        ),
    ]
